# Generated by Django 4.2.2 on 2023-06-16 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_rename_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Participant',
            field=models.ManyToManyField(related_name='Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
