# Generated by Django 4.2.2 on 2023-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_participant_room_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant',
            new_name='Participant',
        ),
    ]
