# Generated by Django 4.2.2 on 2023-06-16 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_rename_participant_room_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Participant',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
